baseURL = "https://Schwarf.github.io/"
languageCode = "en-us"
title = "Welcome to the website of Andreas Scharf"
theme = "nice"
[pagination]
  pagerSize = 2
[params]
  description = "Software Developer and Theoretical Physicist"
